### ISSUE TITLE
Stylish + catppuccin.user.css not working ?

### ISSUE THREAD

**Issue by Crystal4276** [catppuccin/github#36]
Hello,
I tried to install the catppuccin theming with stylish.

I can see when i copy paste catppuccin.user.css in the stylish editor tens of errors marked on the side with warning icons.
Expected Brace, unexpected token etc...
No theming is applied so far.

**Comment by justTOBBI** [comment]
Hey, try opening the theme with the Button 'Stylus Install' this installs the theme as a usertheme.

**Comment by andreasgrafen** [comment]
I haven't used Stylish in years, and damn has it changed.
The issues and warning icons are likely due to the dependency on the Preprocessor. Sadly I can't check the theme through Stylish as it apparently requires an account to apply a style locally …
**It might be that this theme isn't even compatible with the current version of Stylish.** In that case I'd highly suggest to use Stylus instead. It has full compatibility with everything that can be run through Stylish, but offers more flexbibility and features.

**Comment by Crystal4276** [comment]
Hi, 
I went to Stylus instead. 
Thanks you both for the answers.
It might be good to remove the mention of Stylish for the theme installation ?

**Comment by andreasgrafen** [comment]
Yeah, it probably is a remnant from version one of this theme anyway. This also likely affects a lot of our userstyles, not only the GitHub theme. o:
I'll get to it. c:

**Comment by justTOBBI** [comment]
Hey @Crystal4276 do you, by any chance, have Dark Reader installed and not disabled on Github? When I enable Dark Reader it looks the same for me. 
Hope that solves the issue :)

**Comment by Crystal4276** [comment]
Oh !!! Nicely spotted!
Yep looks gorgeous now.

**Comment by nekowinston** [comment]
Closing this since it seems resolved. Please re-open if necessary.
